#[doc = "Register `single_req` reader"]
pub type R = crate::R<SingleReqSpec>;
#[doc = "Register `single_req` writer"]
pub type W = crate::W<SingleReqSpec>;
#[doc = "Field `single_req` reader - Software single request."]
pub type SingleReqR = crate::FieldReader<u16>;
#[doc = "Field `single_req` writer - Software single request."]
pub type SingleReqW<'a, REG> = crate::FieldWriter<'a, REG, 16, u16>;
impl R {
    #[doc = "Bits 0:15 - Software single request."]
    #[inline(always)]
    pub fn single_req(&self) -> SingleReqR {
        SingleReqR::new((self.bits & 0xffff) as u16)
    }
}
impl W {
    #[doc = "Bits 0:15 - Software single request."]
    #[inline(always)]
    #[must_use]
    pub fn single_req(&mut self) -> SingleReqW<SingleReqSpec> {
        SingleReqW::new(self, 0)
    }
}
#[doc = "Software Single Request Register - enables DMA single requests to be generated by software. You can generate a DMA request for each source by writing a 1 to the corresponding register bit. A register bit is cleared when the transaction has completed. Writing 0 to this register has no effect. Reading the register indicates the sources that are requesting single DMA transfers. You can generate a request from either a peripheral or the software request register\n\nYou can [`read`](crate::generic::Reg::read) this register and get [`single_req::R`](R).  You can [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`write_with_zero`](crate::generic::Reg::write_with_zero) this register using [`single_req::W`](W). You can also [`modify`](crate::generic::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct SingleReqSpec;
impl crate::RegisterSpec for SingleReqSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`single_req::R`](R) reader structure"]
impl crate::Readable for SingleReqSpec {}
#[doc = "`write(|w| ..)` method takes [`single_req::W`](W) writer structure"]
impl crate::Writable for SingleReqSpec {
    type Safety = crate::Unsafe;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: u32 = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: u32 = 0;
}
#[doc = "`reset()` method sets single_req to value 0"]
impl crate::Resettable for SingleReqSpec {
    const RESET_VALUE: u32 = 0;
}
